name: icecast_example
description: An example of the Icecast package.
version: 0.0.1
repository: https://github.com/sneurlax/icecast

environment:
  sdk: ^3.2.6

dependencies:
  icecast:
    path: ..
  console: ^4.1.0

dev_dependencies:
  lints: ^2.1.0
