name: icecast
description: Icecast tools for Dart & Flutter
version: 0.0.1
# repository: https://github.com/sneurlax/icecast

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
